<a href="https://colab.research.google.com/github/imeamin/TIL/blob/master/2021_03_17_00_%EC%BB%A8%ED%85%90%EC%B8%A0_%EA%B8%B0%EB%B0%98_%EC%B6%94%EC%B2%9C%EC%8B%9C%EC%8A%A4%ED%85%9C_TF_IDF%EB%A5%BC_%EC%9D%B4%EC%9A%A9%ED%95%9C_%EC%B6%94%EC%B2%9C%EC%8B%9C%EC%8A%A4%ED%85%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
docs=[
      '먹고 싶은 사과', #문서0
      '먹고 싶은 바나나',#문서1
      '길고 노란 바나나 바나나',#문서2
      '저는 과일이 좋아요' #문서3
]
docs

['먹고 싶은 사과', '먹고 싶은 바나나', '길고 노란 바나나 바나나', '저는 과일이 좋아요']

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
vect=CountVectorizer()#Counter Vectorizer 객체 생성

In [7]:
vect

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [8]:
#문장을 Counter Vectorizer 형태로 변형
countvect=vect.fit_transform(docs)
countvect #4x9 :4개의 문서에 9개의 단어

<4x9 sparse matrix of type '<class 'numpy.int64'>'
	with 12 stored elements in Compressed Sparse Row format>

In [9]:
#toarray()를 통해서 문장이 Vector 형태의 값을 얻을 수 있음
#하지만, 각 인덱스와 컬럼이 무엇을 의미하는지에 대해서는 알 수가 없음
#sparse matrix->numpy
#결과 0,1,2 문서 내의 단어가 등장한 횟수에 따라서 부여된 것
countvect.toarray()

array([[0, 0, 0, 1, 0, 1, 1, 0, 0],
       [0, 0, 0, 1, 1, 0, 1, 0, 0],
       [0, 1, 1, 0, 2, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 1, 1]])

In [10]:
vect.vocabulary_

{'과일이': 0,
 '길고': 1,
 '노란': 2,
 '먹고': 3,
 '바나나': 4,
 '사과': 5,
 '싶은': 6,
 '저는': 7,
 '좋아요': 8}

In [11]:
# 각 value가 의미하는게 컬럼의 위치, key는 해당 컬럼의 단어를 의미각 value가 
 #의미하는게 컬럼의 위치, key는 해당 컬럼의 단어를 의미
sorted(vect.vocabulary_)
sorted(vect.vocabulary_)

['과일이', '길고', '노란', '먹고', '바나나', '사과', '싶은', '저는', '좋아요']

In [14]:
import pandas as pd
countvect_df=pd.DataFrame(countvect.toarray(),columns=sorted(vect.vocabulary_))
countvect_df.index=['문서1','문서2','문서3','문서4']
countvect_df

과일이  길고  노란  먹고  바나나  사과  싶은  저는  좋아요
문서1    0   0   0   1    0   1   1   0    0
문서2    0   0   0   1    1   0   1   0    0
문서3    0   1   1   0    2   0   0   0    0
문서4    1   0   0   0    0   0   0   1    1

In [15]:
#위의 Data Frame 형태의 유사도를 계산
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(countvect_df, countvect_df) #문서1과 문서2가 유사하고 문서2와 문서3도 유사하다

array([[1.        , 0.66666667, 0.        , 0.        ],
       [0.66666667, 1.        , 0.47140452, 0.        ],
       [0.        , 0.47140452, 1.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        ]])

In [16]:
#CountVectorizer -> TfidfVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
vect=TfidfVectorizer()
tfvect=vect.fit(docs)

In [17]:
tfidv_df=pd.DataFrame(tfvect.transform(docs).toarray(),columns=sorted(vect.vocabulary_))
tfidv_df.index=['문서1','문서2','문서3','문서4']
tfidv_df

과일이       길고       노란        먹고  ...        사과        싶은       저는      좋아요
문서1  0.00000  0.00000  0.00000  0.526405  ...  0.667679  0.526405  0.00000  0.00000
문서2  0.00000  0.00000  0.00000  0.577350  ...  0.000000  0.577350  0.00000  0.00000
문서3  0.00000  0.47212  0.47212  0.000000  ...  0.000000  0.000000  0.00000  0.00000
문서4  0.57735  0.00000  0.00000  0.000000  ...  0.000000  0.000000  0.57735  0.57735

[4 rows x 9 columns]

In [18]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(tfidv_df,tfidv_df)

array([[1.        , 0.60784064, 0.        , 0.        ],
       [0.60784064, 1.        , 0.42980824, 0.        ],
       [0.        , 0.42980824, 1.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        ]])