#### Simple ID array and slicing

In [3]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

import numpy as np
import pprint

tf.set_random_seed(777)

pp=pprint.PrettyPrinter(indent=4)
sess=tf.InteractiveSession()

t=np.array([0.,1.,2.,3.,4.,5.,6.])
pp.pprint(t)
print(t.ndim) #rank
print(t.shape) #shape
print(t[0],t[1],t[-1])
print(t[2:5],t[4:-1])
print(t[:2],t[3:])

Instructions for updating:
non-resource variables are not supported in the long term
array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


#### 2D Array

In [4]:
t=np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
pp.pprint(t)
print(t.ndim)
print(t.shape)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


- eval(): 문자열로 표현된 파이썬 식을 인수로 받아 파이썬 컴파일 코드로 변환한다.

In [5]:
t=tf.constant([1,2,3,4])
tf.shape(t).eval()

array([4])

In [6]:
t=tf.constant([[1,2],[3,4]])
tf.shape(t).eval()

array([2, 2])

In [7]:
t=tf.constant([
    [
        [
            [1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]
        ],
              [
                  [13,14,15,16],
                  [17,18,19,20],
                  [21,22,23,24]
              ]
    ]
])
tf.shape(t).eval()

array([1, 2, 3, 4])

#### Matmul VS multiply


In [11]:
matrix1=tf.constant([[1.,2.],[3.,4.]])
matrix2=tf.constant([[1.],[2.]])
print("Matrix 1 shape",matrix1.shape)
print("Matrix 2 shape",matrix2.shape)
tf.matmul(matrix1, matrix2).eval()

Matrix 1 shape (2, 2)
Matrix 2 shape (2, 1)


array([[ 5.],
       [11.]], dtype=float32)

#### Broadcasting
- shape이 다르더라도 matrix의 연산이 가능하도록 도와주는 것

In [15]:
# Operations between the same shapes
matrix1 = tf.constant([[3.,3.]])
matrix2=tf.constant([[2.,2.]])
(matrix1+matrix2).eval()

array([[5., 5.]], dtype=float32)

In [16]:
matrix1=tf.constant([[1.,2.]])
matrix2=tf.constant(3.)
(matrix1+matrix2).eval()

array([[4., 5.]], dtype=float32)

In [17]:
matrix1=tf.constant([[1.,2.]])
matrix2=tf.constant([3.,4.])
(matrix1+matrix2).eval()

array([[4., 6.]], dtype=float32)

#### Reduce mean
- 평균을 줄여서 구한다.

In [18]:
tf.reduce_mean([1,2],axis=0).eval()

1

In [19]:
x=[[1.,2.],
  [3.,4.]]

tf.reduce_mean(x).eval()

2.5

In [20]:
tf.reduce_mean(x,axis=0).eval()

array([2., 3.], dtype=float32)

In [21]:
tf.reduce_mean(x,axis=1).eval()

array([1.5, 3.5], dtype=float32)

In [23]:
tf.reduce_sum(x,axis=-1).eval()

array([3., 7.], dtype=float32)

#### Argmax
- 가장 큰 것의 위치

In [24]:
x=[[0,1,2],
  [2,1,0]]
tf.argmax(x,axis=0).eval()

array([1, 0, 0], dtype=int64)

In [25]:
tf.argmax(x,axis=1).eval()

array([2, 0], dtype=int64)

In [26]:
tf.argmax(x,axis=0).eval()

array([1, 0, 0], dtype=int64)

In [27]:
tf.argmax(x,axis=-1).eval()

array([2, 0], dtype=int64)

#### Casting

In [28]:
tf.cast([1.8,2.2,3.3,4.9],tf.int32).eval()

array([1, 2, 3, 4])

In [30]:
tf.cast([True,False,1==1,0==1],tf.float32).eval()

array([1., 0., 1., 0.], dtype=float32)

#### Stack
- 쌓는다

In [31]:
x=[1,4]
y=[2,5]
z=[3,6]

tf.stack([x,y,z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [32]:
tf.stack([x,y,z],axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]])