#### Hypothesis using matrix

- H(x1,x2,x3)=x1w1+x2w2+x3w3

In [6]:
import tensorflow.compat.v1 as tf

tf.disable_v2_behavior()

x1_data=[73,93,89,96,73]
x2_data=[80,88,91,98,66]
x3_data=[75,93,90,100,70]
y_data=[152,185,180,196,142]

#placeholder 설정
x1=tf.placeholder(tf.float32)
x2=tf.placeholder(tf.float32)
x3=tf.placeholder(tf.float32)

Y=tf.placeholder(tf.float32)

#tf.random_normal(): 랜덤으로 표준분포에 따라 값을 배정하고 싶을 때 사용
w1=tf.Variable(tf.random_normal([1]),name='weight1')
w2=tf.Variable(tf.random_normal([1]),name='weight2')
w3=tf.Variable(tf.random_normal([1]),name='weight3')
b=tf.Variable(tf.random_normal([1]),name='bias')

hypothesis=x1*w1+x2*w2+x3*w3+b

#cost/Loss function
cost=tf.reduce_mean(tf.square(hypothesis-Y))
optimizer=tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train=optimizer.minimize(cost)

#Launch the graph in a session
sess=tf.Session()

sess.run(tf.global_variables_initializer())
for step in range(2001):
  cost_val,hy_val,_=sess.run([cost,hypothesis,train],
                             feed_dict={x1:x1_data,x2:x2_data,x3:x3_data,Y:y_data})
  
  if step%10==0:
    print(step,"Cost: ",cost_val,"\nPrediction:\n",hy_val)



0 Cost:  11756.529 
Prediction:
 [58.478813 66.799965 67.703476 73.3904   50.23092 ]
10 Cost:  6.3490996 
Prediction:
 [154.36061 182.06047 181.26242 197.0541  138.14937]
20 Cost:  6.209488 
Prediction:
 [154.64136 182.41563 181.60315 197.42601 138.42395]
30 Cost:  6.177661 
Prediction:
 [154.6329  182.4231  181.60135 197.42491 138.43335]
40 Cost:  6.1459703 
Prediction:
 [154.6236  182.42953 181.59854 197.4227  138.44193]
50 Cost:  6.114482 
Prediction:
 [154.6143  182.43591 181.59572 197.42046 138.45045]
60 Cost:  6.083149 
Prediction:
 [154.60504 182.44229 181.5929  197.41824 138.45897]
70 Cost:  6.0520005 
Prediction:
 [154.59578 182.44862 181.59009 197.41603 138.46745]
80 Cost:  6.02101 
Prediction:
 [154.5866  182.45497 181.5873  197.41382 138.47594]
90 Cost:  5.9901576 
Prediction:
 [154.5774  182.4613  181.5845  197.41159 138.48438]
100 Cost:  5.959514 
Prediction:
 [154.56822 182.46759 181.58171 197.40941 138.4928 ]
110 Cost:  5.928998 
Prediction:
 [154.55908 182.47388 181.57

In [12]:
#Matrix로 구현
import tensorflow.compat.v1 as tf

tf.disable_v2_behavior()

x_data=[[73,80,75],[93,88,93],[89,91,90],[96,98,100],[73,66,70]]
y_data=[[152.],[185.],[180.],[196.],[142.]]

X=tf.placeholder(tf.float32,shape=[None,3])
Y=tf.placeholder(tf.float32,shape=[None,1])

W=tf.Variable(tf.random_normal([3,1]),name='weight')
b=tf.Variable(tf.random_normal([1]),name='bias')

 
hypothesis=tf.matmul(X,W)+b
cost=tf.reduce_mean(tf.square(hypothesis-Y))
optimizer=tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train=optimizer.minimize(cost)

sess=tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
  cost_val,hy_val,_=sess.run(
      [cost,hypothesis,train],feed_dict={X:x_data,Y:y_data}
  )
  if step%10==0:
    print(step,'Cost: ',cost_val,'\nPrediction:\n',hy_val)

0 Cost:  17976.494 
Prediction:
 [[33.337334]
 [41.406693]
 [40.39998 ]
 [40.28694 ]
 [35.005203]]
10 Cost:  2.4905784 
Prediction:
 [[151.93698]
 [183.95248]
 [180.85384]
 [193.23827]
 [143.73073]]
20 Cost:  2.3243442 
Prediction:
 [[152.2969 ]
 [184.38297]
 [181.27905]
 [193.70189]
 [144.05804]]
30 Cost:  2.3226812 
Prediction:
 [[152.29907]
 [184.38345]
 [181.2806 ]
 [193.70415]
 [144.05742]]
40 Cost:  2.3209922 
Prediction:
 [[152.30017]
 [184.38266]
 [181.28084]
 [193.70502]
 [144.05579]]
50 Cost:  2.3193085 
Prediction:
 [[152.30125]
 [184.38185]
 [181.28108]
 [193.70587]
 [144.05414]]
60 Cost:  2.3176455 
Prediction:
 [[152.30232]
 [184.38104]
 [181.28134]
 [193.70673]
 [144.0525 ]]
70 Cost:  2.3160038 
Prediction:
 [[152.3034 ]
 [184.38023]
 [181.28159]
 [193.70758]
 [144.0509 ]]
80 Cost:  2.3143375 
Prediction:
 [[152.30446]
 [184.37944]
 [181.28181]
 [193.70842]
 [144.04927]]
90 Cost:  2.312662 
Prediction:
 [[152.30551]
 [184.37863]
 [181.28204]
 [193.70929]
 [144.04765]]
10