In [1]:
import numpy as np


In [2]:
list=[1,2,3,4,5,6]
arr=np.array(list)
print(arr)
print(arr.shape)

[1 2 3 4 5 6]
(6,)


In [4]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [14]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr)
print(arr[0,0])

(2, 3)
[[1 2 3]
 [4 5 6]]
1


### numpy 배열을 만드는 방법
- zeros()는 해당 배열에 모두 0을 넣어 배열 생성
- ones()는 모두 1을 넣어 배열 생성
- full()은 배열에 사용자가 지정한 값을 넣어 생성
- eye()는 대각선으로는 1이고 나머지는 0인 2차원 배열을 생성

In [17]:
arr=np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
arr=np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
arr=np.eye(5)
arr


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
arr=np.array(range(12)).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
arr=np.array(range(12))
display(arr)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
arr=np.array(range(12)).reshape(3,4)#배열 구조의 곱=데이터 갯수()
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Numpy 슬라이싱
- numpy 배열을 슬라이싱하기 위해서는 각 차원별로 슬라이스 범위를 지정
- 배열 차원별 최소-최대의 범위를 정하여 부분 집합을 구하는 것

In [32]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
display(arr[0:2, 0:2])
display(arr[0:4,1:3])


array([[0, 1],
       [4, 5]])

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

### Numpy 정수 인덱싱
- 각 차원별로 선택되어지는 배열요소의 인덱스들을 일렬로 나열하여 부분집합을 구하는 방식
- 임의의 numpy 배열 a에 대해 a[[row1,row2],[col1,col2]]와 같이 표현
- arr[[0,2],[1,3]]은 정수 인덱싱 ==> arr[0,1]과 arr[2,3]등 2개의 배열 요소를 의미

In [34]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
arr[[0,2],[1,2]]

display(arr[0,1])
arr[2,2]

array([ 1, 10])

In [43]:
print(arr[[0,2],[1,2]])
print(arr[0,1])
print(arr[2,2])
#0, 5, 6, 11을 뽑겠다.
print(arr[[0,1,1,2],[0,1,2,3]])

[ 1 10]
1
10
[ 0  5  6 11]


### numpy 부울린 인덱싱
- 배열 각 요소의 선택여부를 True, False로 표현하는 방식

In [45]:
list=[[1,2,3],
     [4,5,6],
     [7,8,9]]
arr=np.array(list)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
bool_index=np.array([[False,True,False],
                   [True,False,True],[
                       False,True,False
                   ]])
arr[bool_index]#True가 있는 곳만 출력, Fasle는 제외

array([2, 4, 6, 8])

In [47]:
bool_=(arr%2 ==0)

In [50]:
print(arr%2==0)
arr[bool_]

[[False  True False]
 [ True False  True]
 [False  True False]]


array([2, 4, 6, 8])

In [51]:
arr[arr%2==0]

array([2, 4, 6, 8])

### numpy 
- +,-,*,/등의 기본 연산자 사용
- add(),substract(),multiply(),divide() 등의 함수를 사용

- 배열간 연산

In [52]:
arr=np.array([[1,2,3],[4,5,6]])

In [58]:
sum_=np.sum(arr)
prod_=np.product(arr)
print("전체 합: ",sum_)
print("전체 곱: ",prod_)

전체 합:  21
전체 곱:  720


In [59]:
sum0=np.sum(arr,axis=0)  #axis 옵션을 이용해 행(1)과 열(0) 단위 계산  
sum1=np.sum(arr,axis=1)  
print(sum0)
print(sum1)

[5 7 9]
[ 6 15]


### Numpy array 곱: numpy.dot()
- 1차원 행렬: vector
- 2차원 행렬: matrix

In [61]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

np.dot(arr1,arr2) # 1*4+2*5+3*6

32

In [ ]:
arr1=np.array([])

In [75]:
arr1=np.arange(4).reshape(2,2)
arr2=np.arange(4).reshape(2,2)
display(arr1)
display(arr2)


np.dot(arr1,arr2)

array([[0, 1],
       [2, 3]])

array([[0, 1],
       [2, 3]])

array([[ 2,  3],
       [ 6, 11]])

In [77]:
arr1=np.arange(2*2*3).reshape(2,2,3)
arr2=np.array([2,1,0])
display(arr1)
display(arr2)
display(np.dot(arr1,arr2)) 
#[1,10]=[0*2+1*1+0*2, 3*2+4*1+5*0]
#[19,28]=[6*2+7*1+0*8, 9*2+4*1+5*0]

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

array([2, 1, 0])

array([[ 1, 10],
       [19, 28]])